services:
  my_subgraph_calcite:
    build:
      context: .
      dockerfile_inline: |-
        FROM csv_connector:latest
        COPY ./ /etc/connector
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /etc/ndc-calcite
    env_file:
      - .env.local.local.local
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "8083"
        protocol: tcp
    volumes:
      - ./resources/test/sales:/data
      - ./configuration.json:/app/configuration.json
